Feature/paloma/terms
Okage-Company/App_MVP pull request #26
Opened 2021-09-10 12:35 UTC by Florence-Paloma

2021-09-13 13:58 UTC, JimenaEB requested changes

2021-09-13 13:58 UTC, JimenaEB commented on src/api/models.py
> +        get_by_business_buservices_variable = cls.query.filter_by(business_id=business_id)
mejor que con filter_by, cuando trabajamos con el id usa directamente get()
cls.query.get(business_id)

2021-09-13 13:58 UTC, JimenaEB commented on src/front/js/component/terms.jsx
> +			<ol>
Por que ol y etiquetas de tablas como dd, dt o dl?

2021-09-13 13:58 UTC, JimenaEB commented on src/front/js/layout.js
> +								<Demo />
Demo era una vista de ejemplo, deberíamos borrarla

2021-09-13 13:58 UTC, JimenaEB commented on src/front/js/pages/demo.js
> +import React from "react";
Estas yusando fragment y falta importarlo

2021-09-13 13:58 UTC, JimenaEB commented on src/front/js/pages/demo.js
>  export const Demo = () => {
pon mejor otro nombre que demo

2021-09-13 14:45 UTC, Florence-Paloma commented on src/front/js/component/terms.jsx
> +			<ol>
Era para dejarlo numerado, justo como estaba en el drive, pero creo que Ricardo también tiene otro pero con ul

2021-09-13 14:45 UTC, Florence-Paloma commented on src/front/js/layout.js
> +								<Demo />
ok

2021-09-13 14:48 UTC, Florence-Paloma commented on src/front/js/pages/demo.js
> +import React from "react";
Es verdad, pero me compilaba bien la página y no se quejaba :D

2021-09-15 01:23 UTC, Florence-Paloma commented on src/api/models.py
> +        get_by_business_buservices_variable = cls.query.filter_by(business_id=business_id)
hecho

2021-09-15 01:54 UTC, closed without merging